# render.yaml
services:
  - type: web
    name: sql-anywhere-viewer
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4
      - key: RENDER
        value: true
      - key: DB_USER
        value: supervisortopuid
      - key: DB_PASSWORD
        value: thisisthetopuserlevelpwd
      - key: DB_HOST  
        value: 103.118.151.42
      - key: DB_NAME
        value: gm2024

# For manual setup in the Render dashboard
# Build Command: pip install -r requirements.txt
# Start Command: gunicorn wsgi:app
