
services:
  - type: web
    name: sql-anywhere-viewer
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: RENDER
        value: true
      - key: DB_USER
        value: supervisortopuid
      - key: DB_PASSWORD
        value: thisisthetopuserlevelpwd
      - key: DB_HOST  
        value: 103.118.151.42
      - key: DB_NAME
        value: gm2024
